In [1]:
from sympy import Matrix, fraction

def inverse_matrix(matrix):
    m = Matrix(matrix)
    try:
        inv_matrix = m.inv()
        print("Steps to compute the inverse of the matrix:")
        for index, row in enumerate(inv_matrix.tolist()):
            print(f"\nStep {index + 1}: ")
            print(f"{m} * [{'  '.join(str(fraction(x)) for x in row)}] = [1  0  ...  0]")
        return [list(map(fraction, row)) for row in inv_matrix.tolist()]
    except ValueError:
        return "The given matrix does not have an inverse."

In [2]:
inverse_matrix([[-2,1,-1,0],[-1,2,-1,1],[-1,-2,1,2],[0,0,2,2]])

Steps to compute the inverse of the matrix:

Step 1: 
Matrix([[-2, 1, -1, 0], [-1, 2, -1, 1], [-1, -2, 1, 2], [0, 0, 2, 2]]) * [(-2, 3)  (1, 3)  (0, 1)  (-1, 6)] = [1  0  ...  0]

Step 2: 
Matrix([[-2, 1, -1, 0], [-1, 2, -1, 1], [-1, -2, 1, 2], [0, 0, 2, 2]]) * [(1, 9)  (1, 9)  (-1, 3)  (5, 18)] = [1  0  ...  0]

Step 3: 
Matrix([[-2, 1, -1, 0], [-1, 2, -1, 1], [-1, -2, 1, 2], [0, 0, 2, 2]]) * [(4, 9)  (-5, 9)  (-1, 3)  (11, 18)] = [1  0  ...  0]

Step 4: 
Matrix([[-2, 1, -1, 0], [-1, 2, -1, 1], [-1, -2, 1, 2], [0, 0, 2, 2]]) * [(-4, 9)  (5, 9)  (1, 3)  (-1, 9)] = [1  0  ...  0]


[[(-2, 3), (1, 3), (0, 1), (-1, 6)],
 [(1, 9), (1, 9), (-1, 3), (5, 18)],
 [(4, 9), (-5, 9), (-1, 3), (11, 18)],
 [(-4, 9), (5, 9), (1, 3), (-1, 9)]]

In [3]:
import numpy as np

def solve_matrix_equation(A, B, C):
    A = np.array(A)
    B = np.array(B)
    C = np.array(C)
    
    X = np.matmul(np.matmul(np.linalg.inv(B),C),np.linalg.inv(A)) - 3*np.linalg.inv(A) - 2*np.linalg.inv(B)
    
    print("The solution for matrix X:")
    print(X)
A = [[-1, -1], [-1, 0]]
B = [[-1, 0], [-1, 1]]
C = [[2, -1], [0, -1]]
solve_matrix_equation(A, B, C)


The solution for matrix X:
[[ 1.  6.]
 [ 5. -3.]]


In [4]:
import pygame
import random

# Initialize Pygame
pygame.init()

# Set up the display
width = 500
height = 700
screen = pygame.display.set_mode((width, height))

# Define the colors
black = (0, 0, 0)
white = (255, 255, 255)
red = (255, 0, 0)
green = (0, 255, 0)
blue = (0, 0, 255)

# Set up the clock
clock = pygame.time.Clock()

# Set up the tetromino shapes
tetrominoes = [
    [[1, 1, 1, 1]],

    [[2, 0],
     [2, 2],
     [2, 0]],

    [[0, 3, 0],
     [3, 3, 3]],

    [[4, 4, 0],
     [0, 4, 4]],

    [[0, 5, 5],
     [5, 5, 0]],

    [[6, 6, 6],
     [0, 0, 6]],

    [[7, 7],
     [7, 7]]
]

# Choose a random tetromino and set its starting position
current_tetromino = random.choice(tetrominoes)
current_position = [0, int(width / 2 - len(current_tetromino[0]) / 2)]

# Game loop
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # Clear the screen
    screen.fill(black)

    # Draw the tetromino
    for y, row in enumerate(current_tetromino):
        for x, cell in enumerate(row):
            if cell:
                pygame.draw.rect(screen, [red, green, blue, white][cell - 1], (current_position[0] + x, current_position[1] + y, 30, 30), 0)

    # Move the tetromino down
    current_position[1] += 30

    # Update the display
    pygame.display.update()

    # Keep the game running at 60 FPS
    clock.tick(60)

# Quit Pygame
pygame.quit()


ModuleNotFoundError: No module named 'pygame'

In [ ]:
import numpy as np

image = []

# write your code here
inverse = np.linalg.inv(image)
corrected = image @ inverse

# You can use the function "display_image" to display your result
display_image(image)
display_image(corrected)

In [ ]:
encoded_message = '''J'v(ht%suriaw(ygnwhf!b‚(jgwrlgt oqnnymqi!wr|o&f$vvjct(hti$d"tt{qum%juqn }pl&Ueogplr|ooh$htb.'''
split = encoded_message.split('%')
decoded_message = "";
for x in split:
    for i, j in enumerate(x):
        decoded_message += ''.join(chr(ord(j)+16))
print(decoded_message)

In [ ]:
encoded_message = "J'v(ht%suriaw(ygnwhf!b‚(jgwrlgt oqnnymqi!wr|o&f$vvjct(hti$dtt{qum%juqn }pl&Ueogplr|ooh$htb.'"
decoded_message = ''.join(chr(int(i, 16)) for i in x for x in encoded_message.split('%'))
print(decoded_message)


In [ ]:
import numpy as np

image = [[0,-1,1],[1,0,-1],[-1,1,0]]

print(np.array(image) @ np.array([-8,2,-7]))
# write your code here
#inverse = np.linalg.inv(image)
#print(inverse)
#print(np.array(inverse) @ np.array([0,1,0]))

In [ ]:
import numpy.linalg as la
import numpy as np

BC = np.array([[1,2,-3],[1,1,1],[2,-1,0]])
#print(BC)
CC = np.array([[-2,1,-3],[0,1,-1],[-2,0,2]])
#print(CC)
CB = la.inv(BC)
#print(CB) 
print(CB @ CC @ BC)

In [9]:
A = np.array([[1, -1, 1],
             [1, -2, 4], 
             [1, -2, 4], 
             [1, 1, 1] ,
             [1, 2, 4]])

print(A.T @ A)

b = np.array([2,1,2,-4,4])

A.T @ b

[[ 5 -2 14]
 [-2 14 -8]
 [14 -8 50]]


array([ 5, -4, 26])

In [5]:
import numpy as np
import scipy
from scipy.linalg import null_space
A = np.array([[0,0,-1,0],[-1,-1,-1,0]])
ns = scipy.linalg.null_space(A)

#print(ns)

ortho = scipy.linalg.orth(ns,.01)

print(ortho)

[[-0.70710678  0.        ]
 [ 0.70710678  0.        ]
 [ 0.          0.        ]
 [ 0.         -1.        ]]


In [6]:
import numpy as np
import numpy.linalg as la

A = np.array([[1,1,1],[0,1,1],[1,1,0]])
print(A)

la.qr(A, mode = 'reduced')

[[1 1 1]
 [0 1 1]
 [1 1 0]]


(array([[-7.07106781e-01, -3.35470445e-17, -7.07106781e-01],
        [-0.00000000e+00, -1.00000000e+00,  4.74426853e-17],
        [-7.07106781e-01,  3.35470445e-17,  7.07106781e-01]]),
 array([[-1.41421356, -1.41421356, -0.70710678],
        [ 0.        , -1.        , -1.        ],
        [ 0.        ,  0.        , -0.70710678]]))

In [34]:
array = np.array(
    [[1,1,1],
     [0,0,1]])

In [35]:
P, D, Q = la.svd(array)

In [36]:
D

array([1.84775907, 0.76536686])

In [37]:
print(P)


[[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]


In [38]:
print(np.diag(D))

[[1.84775907 0.        ]
 [0.         0.76536686]]


In [39]:
print(Q.T)

[[ 5.00000000e-01 -5.00000000e-01 -7.07106781e-01]
 [ 5.00000000e-01 -5.00000000e-01  7.07106781e-01]
 [ 7.07106781e-01  7.07106781e-01 -2.38984884e-16]]


In [42]:
array = np.array(
    [[1,1,1],
     [0,0,0]])

In [43]:
la.pinv(array)

array([[0.33333333, 0.        ],
       [0.33333333, 0.        ],
       [0.33333333, 0.        ]])

In [54]:
array = np.array(
    [[4.25, 0.25, -2.25, -1.25],
     [0.25, 4.25, -1.25, -2.25],
     [-2.25, -1.25, 4.25, 0.25],
     [-1.25, -2.25, 0.25, 4.25]])
listSVD = np.linalg.svd(array)
u, s, v = listSVD
s = np.diag(s)
s[2][2] = 0
s[3][3] = 0
print(s)
u@s@v

[[8. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[ 3.25,  0.75, -3.25, -0.75],
       [ 0.75,  3.25, -0.75, -3.25],
       [-3.25, -0.75,  3.25,  0.75],
       [-0.75, -3.25,  0.75,  3.25]])